### ISSUE TITLE
Stuck at 100% on any file upload (1.10 rc1)

### ISSUE THREAD

**Issue by mdrzn** [megous/megatools#366]
I've been using the Megatools 1.9.94 for almost two years now, and it always worked flawlessy without even have to check it.
I've noticed lately that it gets stuck at 100% uploads, without closing the connection.

I tried updating to 1.9.98, brand new MEGA account, uploaded one file thru browser and it works, when I try to upload via my VM it hangs at 100% (always at 100%, file is about 90MB, takes 3 secs to upload it then it gets stuck).

I tried with the new version 1.10.0 RC1, same exact issue.
Edit: I've tried both megasync (what I've always been using) to sync a whole folder (always less than 5 files in there) and megaput (on a single file), they both get stuck and never end correctly.

I'm available to give more debug info if needed, I'd just love to fix this. Thanks

**Comment by megous** [comment]
Please try again with rc2. It contains some upload improvements that should help with this.

**Comment by mdrzn** [comment]
Tried with rc2, same megasync of one folder with one file in, gets stuck to 100%. 
Left it for over 90 minutes, nothing happened.
```
 [{
        "a": "u",
        "ssl": 0,
        "ms": 0,
        "s": 95326039,
        "r": 0,
        "e": 0
}]
100% - 90,9 MiB of 90,9 MiB
```

**Comment by megous** [comment]
@mdrzn Thanks for the debug output. It show's you're actually running an older version of megatools, that does not have all of the last week or so of changes.

**Comment by vierirom** [comment]
I have the same problem for some days. different pcs same command line .bat file and all have the same problem. get stuck at 100% never ending the magaput command.
I also updated megatools to version megatools 1.9.98. what wrong ?

**Comment by mdrzn** [comment]
@megous weird, every time I unzip the latest release in a different folder and run that one. 
Maybe since they share the .rcmega login info there's some more "old files" around that are being used by the new rc2?

**Comment by megous** [comment]
@vierirom You're using old version.
@mdrzn I don't know. Run megals --version if you're not sure.

**Comment by mdrzn** [comment]
@megous thanks, it seems like I'm still calling back to the 9.94 version.
I somehow installed and tried the new rc2.0 and it uploaded with no issue at all, 
I appreciate your work a lot!

Now I'll figure out how to point to the new installation.

**Comment by gmstam** [comment]
1.10.0-rc3 also stuck at 100%... How to fix this, please?

**Comment by megous** [comment]
By being patient. There's a timeout that will retry the transfer to a different mega server. You can also try searchig mega.c for boost = TRUE and change it to boost = FALSE if that helps.

**Comment by megous** [comment]
Should be fixed by 1.10.0

**Comment by megous** [comment]
See #365 for details.

**Comment by vierirom** [comment]
1.10.0-rc2 works for me as well.

**Comment by mdrzn** [comment]
Now 1.10.0-rc2 doesn't work, still gets stuck to 100%. I tried downloading the newest 1.10.0, but it fails while installing, after the "make" command:
```
lib/http.c: In function ‘http_set_progress_callback’:
lib/http.c:223:29: error: ‘CURLOPT_XFERINFOFUNCTION’ undeclared (first use in this function)
   curl_easy_setopt(h->curl, CURLOPT_XFERINFOFUNCTION, curl_progress);
                             ^
lib/http.c:223:29: note: each undeclared identifier is reported only once for each function it appears in
lib/http.c:224:29: error: ‘CURLOPT_XFERINFODATA’ undeclared (first use in this function)
   curl_easy_setopt(h->curl, CURLOPT_XFERINFODATA, h);
```

**Comment by gmstam** [comment]
Unfortunately, 1.10.0 still gets stuck to 100%.... I was using these cli tools for months with success in a crontab... but it doesn't work since last 15th July. It's not working also if I manually upload a file.

Here some warning after make -j4:
`lib/mega.c: In function ‘tman_worker_upload_chunk’:
lib/mega.c:3210:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  *((guint64 *)&iv[8]) = GUINT64_TO_BE((guint64)(c->offset / 16)); // this is ok, because chunks are 16b aligned
  ^
lib/mega.c: At top level:
lib/mega.c:1179:13: warning: ‘meta_mac_pack’ defined but not used [-Wunused-function]
 static void meta_mac_pack(guchar meta_mac[16], guchar packed[8])
             ^
  AR       libmega.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     megadl
  CCLD     megaget
  CCLD     megals
  CCLD     megadf
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
  CCLD     megaput
  CCLD     megamkdir
  CCLD     megareg
  CCLD     megarm
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
  CCLD     megacopy
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1`

And here the output after make install:
`/bin/mkdir -p '/home/kasper/.local/bin'
  /usr/bin/install -c megadf megadl megaget megals megamkdir megaput megareg megarm megacopy '/home/kasper/.local/bin'
 /bin/mkdir -p '/home/kasper/.local/share/doc/megatools'
 /usr/bin/install -c -m 644 LICENSE NEWS TODO README INSTALL HACKING '/home/kasper/.local/share/doc/megatools'`

**Comment by gmstam** [comment]
Yes, checked it. 1.10.0

**Comment by gmstam** [comment]
It’s working again since yesterday! Thank you!
